### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'temp_type'

### ISSUE THREAD

**Issue by colino17** [xury77/AirCon#2]
### Issue:
There is an issue caused by the commit to line 297 of "[__main__.py](https://github.com/xury77/AirCon/blob/master/aircon/__main__.py)" which results in the subject error and the config json file to fail to generate.

Note that if the config json already exists the error doesn't occur.

I tested reverting to the previous iteration of that line and the issue disappeared and the config generated properly.

Note that for my region, Canada, we use "fglair-us" which causes the config to generate using F when it should use C. I've had to manually change this in the generated config to get the right values. I suspect these are the type of issues you are looking to solve, however the commit does not seem to be working as expected.

### Current line:
```
        'temp_type': parsed_args.temp_type or  config['temp_type'],
```

### Previous Line:
```python
        'temp_type': config['temp_type'],
```

### Full Error Log:
```python
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "/app/aircon/__main__.py", line 315, in <module>

    asyncio.run(discovery(parsed_args))

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete

    return future.result()

  File "/app/aircon/__main__.py", line 297, in discovery

    'temp_type': parsed_args.temp_type or  config['temp_type'],

AttributeError: 'Namespace' object has no attribute 'temp_type'
```

**Comment by xury77** [comment]
Because I'm far from Python. I just wanted to make some simple fixes in this probably abandoned repo. So let's get back to a working version.
